export const I18N = {
    en: {
        title: 'Kindle EPUB Fix',
        subtitle: 'Premium E-book Optimization Tool',
        description: 'Prepare your EPUB files for "Send to Kindle" by fixing encoding errors, unresolved hyperlinks, and missing metadata.',
        privacy: 'Privacy: All processing happens in your browser. Your files are never uploaded.',
        upload: 'Drag & drop EPUB files here',
        upload_hint: 'or click to browse your computer',
        bulk: 'Bulk Metadata Edit',
        history: 'Recent History',
        done: 'Finished processing all files.',
        no_error: 'No errors detected.',
        sys_error: 'Internal system error.',
        processing: 'Processing...',
        download: 'Download',
        download_all: 'Download all as ZIP',
        edit_meta: 'Edit Meta',
        preview: 'Preview',
        save: 'Save',
        cancel: 'Cancel',
        kindle_mail: '✉️ Kindle',
        bulk_meta_applied: 'Applied bulk changes to {n} files.',
        // Feature Titles
        feat_enc_title: 'UTF-8 Encoding',
        feat_enc_desc: 'Adds missing UTF-8 declarations to fix special character rendering.',
        feat_link_title: 'Hyperlink Fix',
        feat_link_desc: 'Resolves NCX table of content links that Amazon often rejects.',
        feat_meta_title: 'Metadata Validation',
        feat_meta_desc: 'Detects invalid language tags and helps you correct them.',
        feat_html_title: 'HTML Cleanup',
        feat_html_desc: 'Removes stray image tags and other common formatting issues.',
        // Metadata Labels
        meta_title: 'Title',
        meta_author: 'Author',
        meta_series: 'Series',
        meta_language: 'Language',
        // Changelog
        changelog_title: 'Version History',
        v2_header: 'v2.0 - Current',
        v2_desc: '🚀 Full modular refactor with ES6 modules',
        v2_4k: '🖥️ 4K Display optimization with 5x container width',
        v2_parallel: '⚡ Parallel EPUB processing using Promise.all',
        v2_theme: '🌓 Dark/Light theme with smooth transitions',
        v2_i18n: '🌐 Real-time PT/EN localization system',
        v2_toc: '🛠️ Improved TOC generation with OPF auto-repair',
        v2_icons: '📊 Detailed optimization status with Lucide icons',
        v1_header: 'v1.5',
        v1_bulk: '📦 Bulk processing support',
        v1_meta: '📝 In-browser metadata editor',
        v1_preview: '📖 EPUB reader preview',
        v1_design: '💅 Apple-inspired Design System',
        // Extra
        no_cover: 'No Cover',
        unknown: 'Unknown',
        tooltip_applied: 'Fixed by this tool',
        tooltip_verified: 'Already correct in original file',
        tooltip_warning: 'Could not be fixed',
        tooltip_skipped: 'Not applicable',
        // Result Cards
        opt_metadata: 'Metadata updated',
        opt_lang_verified: 'Language ({n})',
        opt_lang_applied: 'Language auto-detected: {n}',
        opt_encoding_applied: 'UTF-8 encoding fixed in {n} files',
        opt_encoding_verified: 'UTF-8 encoding',
        opt_body_id_applied: 'Fixed {n} body ID links',
        opt_body_id_verified: 'Body ID links',
        opt_stray_img_applied: 'Removed {n} stray images',
        opt_stray_img_verified: 'Image tags',
        opt_toc_verified: 'Table of Contents',
        opt_toc_warning: 'No headings found for TOC',
        opt_toc_applied: 'Generated TOC with {n} entries',
        opt_toc_applied_skip: 'Generated TOC file ({n} entries) - OPF registration skipped',
        opt_toc_applied_fail: 'Generated TOC file ({n} entries) - OPF registration failed',
        opt_links_applied: 'Fixed {n} broken links',
        opt_links_verified: 'Internal links',
        opt_css_applied: 'CSS optimized for e-ink ({n} files)',
        opt_css_verified: 'CSS e-ink compatibility',
        opt_split_applied: 'Chapter splitting verified',
        opt_page_flip_applied: 'Kindle PageFlip metadata added',
        opt_a11y_applied: 'Added {n} alt attributes',
        opt_a11y_verified: 'Image accessibility',
        opt_images_applied: 'Compressed {n} large images',
        opt_images_verified: 'Image sizes',
        opt_fonts_applied: 'Removed {n} embedded fonts',
        opt_fonts_verified: 'Embedded fonts',
        opt_cover_applied: 'Cover image updated',
        // UI Extra
        preparing_zip: 'Preparing ZIP...',
        err_processing: 'Processing failed',
        err_unknown: 'Unknown error'
    },
    pt: {
        title: 'Corretor EPUB Kindle',
        subtitle: 'Ferramenta Premium de Otimização de E-books',
        description: 'Prepare seus arquivos EPUB para "Enviar para Kindle" corrigindo erros de codificação, hiperlinks não resolvidos e metadados ausentes.',
        privacy: 'Privacidade: Todo o processamento acontece no seu navegador. Seus arquivos nunca são enviados.',
        upload: 'Arraste arquivos EPUB aqui',
        upload_hint: 'ou clique para navegar no seu computador',
        bulk: 'Edição de Metadados em Massa',
        history: 'Histórico Recente',
        done: 'Processamento concluído.',
        no_error: 'Nenhum erro detectado.',
        sys_error: 'Erro interno do sistema.',
        processing: 'Processando...',
        download: 'Download',
        download_all: 'Baixar tudo como ZIP',
        edit_meta: 'Editar Metadados',
        preview: 'Pré-visualização',
        save: 'Salvar',
        cancel: 'Cancelar',
        kindle_mail: '✉️ Kindle',
        bulk_meta_applied: 'Alterações em massa aplicadas a {n} arquivos.',
        // Titulos de Funcionalidades
        feat_enc_title: 'Codificação UTF-8',
        feat_enc_desc: 'Adiciona declarações UTF-8 ausentes para corrigir a renderização de caracteres especiais.',
        feat_link_title: 'Correção de Links',
        feat_link_desc: 'Resolve links de sumário NCX que a Amazon costuma rejeitar.',
        feat_meta_title: 'Validação de Metadados',
        feat_meta_desc: 'Detecta tags de idioma inválidas e ajuda a corrigi-las.',
        feat_html_title: 'Limpeza HTML',
        feat_html_desc: 'Remove tags de imagem perdidas e outros problemas comuns de formatação.',
        // Metadados
        meta_title: 'Título',
        meta_author: 'Autor',
        meta_series: 'Série',
        meta_language: 'Idioma',
        // Changelog
        changelog_title: 'Histórico de Versões',
        v2_header: 'v2.0 - Atual',
        v2_desc: '🚀 Refatoração modular com módulos ES6',
        v2_4k: '🖥️ Otimização para telas 4K (largura de 2200px)',
        v2_parallel: '⚡ Processamento paralelo com Promise.all',
        v2_theme: '🌓 Tema Claro/Escuro com transições suaves',
        v2_i18n: '🌐 Sistema de localização PT/EN em tempo real',
        v2_toc: '🛠️ Geração de sumário com auto-reparo de OPF',
        v2_icons: '📊 Status de otimização detalhado com ícones Lucide',
        v1_header: 'v1.5',
        v1_bulk: '📦 Suporte a processamento em lote',
        v1_meta: '📝 Editor de metadados no navegador',
        v1_preview: '📖 Pré-visualização com leitor integrado',
        v1_design: '💅 Design inspirado na Apple',
        // Extra
        no_cover: 'Sem Capa',
        unknown: 'Desconhecido',
        tooltip_applied: 'Corrigido por esta ferramenta',
        tooltip_verified: 'Já estava correto no arquivo original',
        tooltip_warning: 'Não pôde ser corrigido',
        tooltip_skipped: 'Não aplicável',
        // Result Cards
        opt_metadata: 'Metadados atualizados',
        opt_lang_verified: 'Idioma ({n})',
        opt_lang_applied: 'Idioma autodetectado: {n}',
        opt_encoding_applied: 'Codificação UTF-8 corrigida em {n} arquivos',
        opt_encoding_verified: 'Codificação UTF-8',
        opt_body_id_applied: 'Corrigidos {n} links de ID de corpo',
        opt_body_id_verified: 'Links de ID de corpo',
        opt_stray_img_applied: 'Removidas {n} imagens perdidas',
        opt_stray_img_verified: 'Tags de imagem',
        opt_toc_verified: 'Sumário',
        opt_toc_warning: 'Nenhum título encontrado para o sumário',
        opt_toc_applied: 'Sumário gerado com {n} entradas',
        opt_toc_applied_skip: 'Sumário gerado ({n} entradas) - registro no OPF ignorado',
        opt_toc_applied_fail: 'Sumário gerado ({n} entradas) - falha no registro no OPF',
        opt_links_applied: 'Corrigidos {n} links quebrados',
        opt_links_verified: 'Links internos',
        opt_css_applied: 'CSS otimizado para e-ink ({n} arquivos)',
        opt_css_verified: 'Compatibilidade CSS e-ink',
        opt_split_applied: 'Divisão de capítulos verificada',
        opt_page_flip_applied: 'Metadados Kindle PageFlip adicionados',
        opt_a11y_applied: 'Adicionados {n} atributos alt',
        opt_a11y_verified: 'Acessibilidade de imagens',
        opt_images_applied: 'Comprimidas {n} imagens grandes',
        opt_images_verified: 'Tamanhos de imagem',
        opt_fonts_applied: 'Removidas {n} fontes embutidas',
        opt_fonts_verified: 'Fontes embutidas',
        opt_cover_applied: 'Capa atualizada',
        // UI Extra
        preparing_zip: 'Preparando ZIP...',
        err_processing: 'Falha no processamento',
        err_unknown: 'Erro desconhecido'
    },
    es: {
        title: 'Corrector EPUB Kindle',
        subtitle: 'Herramienta Premium de Optimización de Libros Electrónicos',
        description: 'Prepare sus archivos EPUB para "Send to Kindle" corrigiendo errores de codificación, hipervínculos no resueltos y metadados faltantes.',
        privacy: 'Privacidad: Todo el procesamiento ocurre en su navegador. Sus archivos nunca se suben.',
        upload: 'Arrastre y suelte archivos EPUB aquí',
        upload_hint: 'o haga clic para buscar en su computadora',
        bulk: 'Edición de Metadados en Masa',
        history: 'Historial Reciente',
        done: 'Procesamiento de todos los archivos finalizado.',
        no_error: 'No se detectaron errores.',
        sys_error: 'Error interno del sistema.',
        processing: 'Procesando...',
        download: 'Descargar',
        download_all: 'Descargar todo como ZIP',
        edit_meta: 'Editar Metadados',
        preview: 'Vista previa',
        save: 'Guardar',
        cancel: 'Cancelar',
        kindle_mail: '✉️ Kindle',
        bulk_meta_applied: 'Cambios masivos aplicados a {n} archivos.',
        // Títulos de Funcionalidades
        feat_enc_title: 'Codificación UTF-8',
        feat_enc_desc: 'Agrega declaraciones UTF-8 faltantes para corregir la representación de caracteres especiales.',
        feat_link_title: 'Corrección de Hipervínculos',
        feat_link_desc: 'Resuelve los enlaces de la tabla de contenidos NCX que Amazon suele rechazar.',
        feat_meta_title: 'Validación de Metadados',
        feat_meta_desc: 'Detecta etiquetas de idioma no válidas y le ayuda a corregirlas.',
        feat_html_title: 'Limpieza HTML',
        feat_html_desc: 'Elimina etiquetas de imagen perdidas y otros problemas de formato comunes.',
        // Etiquetas de Metadados
        meta_title: 'Título',
        meta_author: 'Autor',
        meta_series: 'Serie',
        meta_language: 'Idioma',
        // Changelog
        changelog_title: 'Historial de Versiones',
        v2_header: 'v2.0 - Actual',
        v2_desc: '🚀 Refactorización modular completa con módulos ES6',
        v2_4k: '🖥️ Optimización de pantalla 4K (ancho de 2200px)',
        v2_parallel: '⚡ Procesamiento de EPUB en paralelo usando Promise.all',
        v2_theme: '🌓 Tema Oscuro/Claro con transiciones suaves',
        v2_i18n: '🌐 Sistema de localización PT/EN/ES en tiempo real',
        v2_toc: '🛠️ Generación de TOC mejorada con autoreparación de OPF',
        v2_icons: '📊 Estado de optimización detallado con iconos de Lucide',
        v1_header: 'v1.5',
        v1_bulk: '📦 Soporte de procesamiento por lotes',
        v1_meta: '📝 Editor de metadados en el navegador',
        v1_preview: '📖 Vista previa del lector de EPUB',
        v1_design: '💅 Sistema de diseño inspirado en Apple',
        // Extra
        no_cover: 'Sin Portada',
        unknown: 'Desconocido',
        tooltip_applied: 'Corregido por esta herramienta',
        tooltip_verified: 'Ya era correcto en el archivo original',
        tooltip_warning: 'No se pudo corregir',
        tooltip_skipped: 'No aplicable',
        // Result Cards
        opt_metadata: 'Metadados actualizados',
        opt_lang_verified: 'Idioma ({n})',
        opt_lang_applied: 'Idioma detectado: {n}',
        opt_encoding_applied: 'Codificación UTF-8 corregida en {n} archivos',
        opt_encoding_verified: 'Codificación UTF-8',
        opt_body_id_applied: 'Corregidos {n} enlaces de ID de cuerpo',
        opt_body_id_verified: 'Enlaces de ID de cuerpo',
        opt_stray_img_applied: 'Eliminadas {n} imágenes perdidas',
        opt_stray_img_verified: 'Etiquetas de imagen',
        opt_toc_verified: 'Índice de contenidos',
        opt_toc_warning: 'No se encontraron títulos para el índice',
        opt_toc_applied: 'Índice generado con {n} entradas',
        opt_toc_applied_skip: 'Índice generado ({n} entradas) - registro en OPF omitido',
        opt_toc_applied_fail: 'Índice generado ({n} entradas) - fallo en registro en OPF',
        opt_links_applied: 'Corregidos {n} enlaces rotos',
        opt_links_verified: 'Enlaces internos',
        opt_css_applied: 'CSS optimizado para e-ink ({n} archivos)',
        opt_css_verified: 'Compatibilidad CSS e-ink',
        opt_split_applied: 'División de capítulos verificada',
        opt_page_flip_applied: 'Metadatos Kindle PageFlip añadidos',
        opt_a11y_applied: 'Añadidos {n} atributos alt',
        opt_a11y_verified: 'Accesibilidad de imagen',
        opt_images_applied: 'Comprimidas {n} imágenes grandes',
        opt_images_verified: 'Tamaños de imagen',
        opt_fonts_applied: 'Eliminadas {n} fuentes incrustadas',
        opt_fonts_verified: 'Fuentes incrustadas',
        opt_cover_applied: 'Portada actualizada',
        // UI Extra
        preparing_zip: 'Preparando ZIP...',
        err_processing: 'Error en el procesamiento',
        err_unknown: 'Error desconocido'
    }
};
